### ISSUE TITLE
Upload TEAM Engine and ETS artefacts to Central Maven Repository

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-docker#2]
All artefacts of TEAM Engine and ETS should be uploaded to Central Maven Repository. This includes ctl scripts and zipped artefacts (e.g. teamengine-console-base.zip).

Currently, just jar files are uploaded to Central Maven Repository [1].

If those artifacts are not uploaded, the Docker project can just be used if all artifacts are built locally. Chapter "Dependencies" [2] can be removed from setup when this issue is solved. Also, further ETS can be added to Docker project.

For example, following artefacts are needed:
```
    <dependency>
      <groupId>org.opengis.cite.teamengine</groupId>
      <artifactId>teamengine-web</artifactId>
      <version>${teamengine.version}</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite.teamengine</groupId>
      <artifactId>teamengine-web</artifactId>
      <version>${teamengine.version}</version>
      <classifier>common-libs</classifier>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite.teamengine</groupId>
      <artifactId>teamengine-console</artifactId>
      <version>${teamengine.version}</version>
      <classifier>base</classifier>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite</groupId>
      <artifactId>ets-wfs20</artifactId>
      <version>${ets-wfs20.version}</version>
      <classifier>ctl</classifier>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite</groupId>
      <artifactId>ets-wfs20</artifactId>
      <version>${ets-wfs20.version}</version>
      <classifier>deps</classifier>
      <type>zip</type>
    </dependency>
```

[1] https://search.maven.org/#search%7Cga%7C1%7Corg.opengis.cite
[2] https://github.com/opengeospatial/teamengine-docker/blob/master/README.md

**Comment by rjmartell** [comment]
The CTL script for the latest WFSv2 test suite release (1.26) is now available in Maven Central:

https://repo.maven.apache.org/maven2/org/opengis/cite/ets-wfs20/1.26/ets-wfs20-1.26-ctl.zip

However, the CTL wrapper script is not required to execute the test suite. The "all-in-one" (-aio.jar) archive can be run in a command shell, or the REST API can be used to invoke the suite by submitting a simple GET/POST request.

**Comment by dstenger** [comment]
Thank you.
As the teaminge-docker project uses the TEAM Engine webapp, the CTL scripts are required.

How is the process of uploading releases of test suites to central maven repository organized? Now, also further test suites (e.g. ets.wms13) should be uploaded.

Also, is it possible to upload all TEAM Engine artefacts (see description of issue)?

**Comment by lgoltz** [comment]
The process how to deploy artefacts on Central Maven Repository is documented in https://github.com/opengeospatial/cite-private/wiki/How-to-deploy-on-Central-Maven-Repository 

Uploading artefacts is work in progress.

**Comment by dstenger** [comment]
All new artefacts are already uploaded to Central Maven Repository.
