### ISSUE TITLE
Create teamengine-docker modules for production and beta environments and remove all other modules

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-docker#24]
Tasks:
1. Create a new module `teamengine-production` and add all ETS which are currently installed on production environment to Dockerfile. `teamengine-ets-all` module can be used as template.
   * Hint: Versions of all ETS can be found here: https://github.com/opengeospatial/teamengine-builder/blob/master/production-releases/201706.csv
1. Create a new module `teamengine-beta` and add all ETS which are currently installed on beta environment to Dockerfile. `teamengine-ets-all` module can be used as template.
   * Hint: Versions of all ETS can be found here: https://github.com/opengeospatial/teamengine-builder/blob/master/beta-releases/201808.csv
1. Remove all modules from project except of the two just created.

Please do all of the work on a new feature branch.

**Comment by keshavnangare** [comment]
@dstenger 

How we can maintain the ets-version as they are different on production and beta? Should we maintain separately according to a module or keep as it is in parent pom?

**Comment by dstenger** [comment]
@keshav-nangare 
Thank you for your work.
In addition, I did some refactorings.

Also, I moved the version properties to sub modules.
Can you please update all version properties so that they match current status of production [1] and beta [2] environment? Obsolete dependencies can be deleted.

[1] http://cite.opengeospatial.org/teamengine/
[2] http://cite.opengeospatial.org/te2/

**Comment by keshavnangare** [comment]
@dstenger 

I have updated the version properties as per the current status of beta and production. Also added missing beta ets in docker.

**Comment by dstenger** [comment]
@keshav-nangare 
Thank you!
Can you please also add new ets-gpkg12 test suite to production module (was moved to production in December)?
In addition, can you please remove properties from production module which are not needed by production image (e.g. ets-wfs30.version)?

**Comment by keshavnangare** [comment]
@dstenger 

Added new ets-gpkg12 to prod and removed properties which are not required for production.
