### ISSUE TITLE
Remove Example.net test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-docker#31]

**Comment by ghobona** [comment]
@kstegemoller Please note that we plan to remove Example.net from the docker image.

**Comment by dstenger** [comment]
Was solved by @kstegemoller.

**Comment by ghobona** [comment]
@kstegemoller How did you solve this? Could you please create a Pull Request based on your solution?

**Comment by dstenger** [comment]
Is already solved.
