### ISSUE TITLE
Create Jenkins pipeline for stopping and restarting TEAM Engine instances

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/teamengine-docker#37]
- [x] Create Jenkins pipeline for stopping and restarting Production TEAM Engine instance, without needing to reinstall
- [x] Create Jenkins pipeline for stopping and restarting Beta TEAM Engine instance, without needing to reinstall

**Comment by dstenger** [comment]
Jenkinsfiles were created: https://github.com/opengeospatial/teamengine-docker/commit/e21712d3728c2a84c9fce3da7d5a0042f63003f2

Also, the folder structure of install Jenkinsfiles was updated: https://github.com/opengeospatial/teamengine-docker/commit/13987a924d9b8f69c63343b96b78a020566f5183
