### ISSUE TITLE
Wrong path for users directory in README

### ISSUE THREAD

**Issue by HusseinKabbout** [opengeospatial/teamengine-docker#40]
I am using the docker image `ogccite/teamengine-production` with the `latest` tag.

When I register a new user then this user is stored in `/usr/local/tomcat/te_base/users`. According to the [documentation](https://github.com/opengeospatial/teamengine-docker#mount-user-data-from-host-system), new users should be stored in `/root/te_base/users`. Which one should be correct?

**Comment by dstenger** [comment]
Thank you for reporting.

Indeed, the documentation was outdated and I updated it: https://github.com/opengeospatial/teamengine-docker/commit/f850d5f4f65573d54fa3251336c009a542cfcf93
